# Generated by Django 5.2.3 on 2025-06-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel_dificultad', models.IntegerField()),
                ('contenido', models.JSONField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicios.categoriacognitiva')),
            ],
        ),
    ]
